### ISSUE TITLE
Renaming class name removes '~' in destructor

### ISSUE THREAD

**Issue by hgijeon** [jomiller/vscode-rtags#26]
With this original code,
`class SomeClass
{
    ~SomeClass() {}
};`

I tried to rename(shortcut: F2) symbol 'SomeClass' into 'ChangedName', but the '~' in the destructor is removed and last character of symbol remained like below.
`class ChangedName
{
    ChangedNames() {}
};`

I'm using rdm with version 2.21.126

**Comment by jomiller** [comment]
This is fixed in 85014ff91c732acb76af765b28ee8f8dbd1354ee. The fix will be included in the next release. Thanks!

**Comment by jomiller** [comment]
@hgijeon, please try out the fix in the new [v0.5.0](https://github.com/jomiller/vscode-rtags/releases/tag/v0.5.0) release, and close this ticket if it looks good.

**Comment by hgijeon** [comment]
Thanks a lot!
