### ISSUE TITLE
Setting 'rtags.misc.compilationDatabaseDirectory' cannot find the database with './build'

### ISSUE THREAD

**Issue by hgijeon** [jomiller/vscode-rtags#27]
The extension shows an error message 'compilation database not found' when I click/load c++ source files.

My '.vscode/settings.json'
`{
    "rtags.misc.compilationDatabaseDirectory": "./build",
}`

**Comment by jomiller** [comment]
This issue is fixed in 1e2f4a06ba3fa8193bcd77808f928583909c5cc3. The fix will be included in the next release. Thanks!

**Comment by jomiller** [comment]
@hgijeon, please try out the fix in the new [v0.5.0](https://github.com/jomiller/vscode-rtags/releases/tag/v0.5.0) release, and close this ticket if it looks good.
